services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: brolly_frontend_dev
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: brolly_frontend_prod
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production